### ISSUE TITLE
hello, I am working on poring android kernel to RISC-V, do you have interest on this?

### ISSUE THREAD

**Issue by unicornx** [nathanchance/android-kernel-clang#18]
Hello, as mentioned in the title of this issue, I'm trying to figure this out. And I believe as a precondition, I have to use clang on building android kernel. That's why I come here and query if you guys have the similar interest as me :)

**Comment by luka177** [comment]
Android kernel is linux. It work on risc

**Comment by unicornx** [comment]
thanks, I will close this issue.
