### ISSUE TITLE
compile other version of android kernel

### ISSUE THREAD

**Issue by xiaoyue10131748** [nathanchance/android-kernel-clang#19]
Hi Nathan,

May I ask a question about compilation other version of android kernel?

Followed by this tutorial, I can successfully compile android-4.4 and android-4.9. However, Is it possible to compile any versions of android kernel(eg., 4.10.0)  if I properly add the Clang commits to this kernel source ?

Best,
Yue

**Comment by nathanchance** [comment]
I do not know of a 4.10.0 Android kernel. All of the Android kernels are based on the LTS branches from kernel.org and all of the currently supported ones have clang support at tip of tree. Feel free to give it a shot but I am not going to be solving any bugs from that endeavor :)
