### ISSUE TITLE
vdsomunge: Not a shared object

### ISSUE THREAD

**Issue by nift4** [nathanchance/android-kernel-clang#22]
Hi! I am trying to fix various warnings on my kernel and am currently compiling with proton clang. If I use GCC4 together with clang, it compiles just fine. If I however use https://github.com/arter97/arm64-gcc (GCC 10) with Clang, I just get
```
arch/arm64/kernel/vdso32/../../../arm/vdso/vdsomunge: Not a shared object
```

Compiling with GCC10 alone is fine.

**Comment by nift4** [comment]
the error comes from here: https://github.com/nift4/OptimKernel/blob/clang-rebase-3/arch/arm/vdso/vdsomunge.c#L153

**Comment by nathanchance** [comment]
Just stick with Proton Clang, it has up to date versions of binutils so you do not need to use the versions that are in that GCC 10.

**Comment by nift4** [comment]
Uh, I am using proton clang. And if the GCC tools get used, the proton clang ones get ignored, don't they? But I don't get why, I followed your instructions exactly.

**Comment by nathanchance** [comment]
I am not sure that I understand. Just use `CC=clang CROSS_COMPILE=aarch64-linux-gnu-` with Proton Clang's `bin` folder in `PATH` and everything should work fine.

**Comment by nift4** [comment]
Thanks! I used an different cross_compile
