### ISSUE TITLE
Kernel panic due to broken patch

### ISSUE THREAD

**Issue by nift4** [nathanchance/android-kernel-clang#23]
After applying clang patches, I decicded to first do an regular GCC4 build to sort out issues with the patches. Well, I got a kernel panic about accessing userspace memory after it tried to play the touch sound. After way to much debugging, I found the problematic patch:
https://github.com/nift4/OptimKernel/commit/da944ad17b69df71441fbe997bfebb3d0eb11fab
I tried this alternative commit:
https://github.com/nift4/OptimKernel/commit/fd1ac4edec2e95345ab346a496ba49e78efe45b5
It doesn't crash anymore, but sound remains silent. Completely.
(I still use GCC 4!)
Without any of those 2 patches, it's fine again. No crash and no silence.

Well, how to properly fix the warning?

**Comment by nift4** [comment]
I was able to fix it by reverting your patch and adding mine:
https://github.com/nift4/OptimKernel/commit/c5a078b4cd8dfce80bd4f1f1e654db6c06c73b5c

phew, that was actually hard to figure out. I'm leaving this open to avoid other people run into this issue due to the broken patch is still in `msm-3.18-android-10` and potentially others.

**Comment by nift4** [comment]
@nathanchance
sorry if this feels impatient, just pinging to make sure you get an notification.

**Comment by nathanchance** [comment]
Yes, sorry, this is known. Unfortunately, I do not really have time to maintain this repo so I am not going to be updating the branches. I can leave this open for people to see more easily.

**Comment by nift4** [comment]
You can pin issues so it won't get lost

**Comment by nift4** [comment]
then it also can be closed. it still is pinned.
