### ISSUE TITLE
Failed to build qcacld-2.0 on Google latest clang9

### ISSUE THREAD

**Issue by yukkodesu** [nathanchance/android-kernel-clang#8]
![IMG_20191219_204910](https://user-images.githubusercontent.com/17264509/71174816-0825de80-22a1-11ea-90c5-49ae6bc87c8f.jpg)
problem showed like this.
Is it clang version to blame?

**Comment by yukkodesu** [comment]
3.18 kernel

**Comment by nathanchance** [comment]
I assume you found the answer since you closed the issue but this would be the fix: https://github.com/nathanchance/marlin/commit/9929a04e853edb11ccc324bdeaa0594d078f515c

**Comment by yukkodesu** [comment]
Yes, I found it cflags problem.
Very grateful to your reply
