### ISSUE TITLE
Kernel 3.18.y patch missing！

### ISSUE THREAD

**Issue by h1jacker** [nathanchance/android-kernel-clang#9]
Can't find the 3.18.y kernel patch ，i don't know where to find about that, could you tell me？

**Comment by nathanchance** [comment]
There are three 3.18 branches for Oreo, Pie, and 10.

**Comment by h1jacker** [comment]
Don't have about nougat？ @nathanchance

**Comment by nathanchance** [comment]
No, Nougat kernels are ancient and I am not interested in supporting them through this repo.

**Comment by h1jacker** [comment]
Okey , thank you anyway
